/* Generated by Yosys 0.9+3621 (git sha1 84e9fa7, gcc 8.3.1 -fPIC -Os) */

module user_project_wrapper(user_clock2, wb_clk_i, wb_rst_i, wbs_ack_o, wbs_cyc_i, wbs_stb_i, wbs_we_i, vccd1, vssd1, vccd2, vssd2, vdda1, vssa1, vdda2, vssa2, analog_io, io_in, io_oeb, io_out, la_data_in, la_data_out, la_oen, wbs_adr_i, wbs_dat_i, wbs_dat_o, wbs_sel_i);
  inout [30:0] analog_io;
  input [37:0] io_in;
  output [37:0] io_oeb;
  output [37:0] io_out;
  input [127:0] la_data_in;
  output [127:0] la_data_out;
  input [127:0] la_oen;
  input user_clock2;
  input vccd1;
  input vccd2;
  input vdda1;
  input vdda2;
  input vssa1;
  input vssa2;
  input vssd1;
  input vssd2;
  input wb_clk_i;
  input wb_rst_i;
  output wbs_ack_o;
  input [31:0] wbs_adr_i;
  input wbs_cyc_i;
  input [31:0] wbs_dat_i;
  output [31:0] wbs_dat_o;
  input [3:0] wbs_sel_i;
  input wbs_stb_i;
  input wbs_we_i;
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[0]  (
    .DIODE(io_in[0]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[10]  (
    .DIODE(io_in[10]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[11]  (
    .DIODE(io_in[11]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[12]  (
    .DIODE(io_in[12]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[13]  (
    .DIODE(io_in[13]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[14]  (
    .DIODE(io_in[14]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[15]  (
    .DIODE(io_in[15]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[16]  (
    .DIODE(io_in[16]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[17]  (
    .DIODE(io_in[17]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[18]  (
    .DIODE(io_in[18]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[19]  (
    .DIODE(io_in[19]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[1]  (
    .DIODE(io_in[1]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[20]  (
    .DIODE(io_in[20]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[21]  (
    .DIODE(io_in[21]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[22]  (
    .DIODE(io_in[22]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[23]  (
    .DIODE(io_in[23]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[24]  (
    .DIODE(io_in[24]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[25]  (
    .DIODE(io_in[25]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[26]  (
    .DIODE(io_in[26]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[27]  (
    .DIODE(io_in[27]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[28]  (
    .DIODE(io_in[28]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[29]  (
    .DIODE(io_in[29]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[2]  (
    .DIODE(io_in[2]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[30]  (
    .DIODE(io_in[30]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[31]  (
    .DIODE(io_in[31]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[32]  (
    .DIODE(io_in[32]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[33]  (
    .DIODE(io_in[33]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[34]  (
    .DIODE(io_in[34]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[35]  (
    .DIODE(io_in[35]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[36]  (
    .DIODE(io_in[36]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[37]  (
    .DIODE(io_in[37]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[3]  (
    .DIODE(io_in[3]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[4]  (
    .DIODE(io_in[4]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[5]  (
    .DIODE(io_in[5]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[6]  (
    .DIODE(io_in[6]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[7]  (
    .DIODE(io_in[7]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[8]  (
    .DIODE(io_in[8]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_io_in[9]  (
    .DIODE(io_in[9]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[0]  (
    .DIODE(la_data_in[0]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[100]  (
    .DIODE(la_data_in[100]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[101]  (
    .DIODE(la_data_in[101]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[102]  (
    .DIODE(la_data_in[102]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[103]  (
    .DIODE(la_data_in[103]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[104]  (
    .DIODE(la_data_in[104]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[105]  (
    .DIODE(la_data_in[105]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[106]  (
    .DIODE(la_data_in[106]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[107]  (
    .DIODE(la_data_in[107]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[108]  (
    .DIODE(la_data_in[108]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[109]  (
    .DIODE(la_data_in[109]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[10]  (
    .DIODE(la_data_in[10]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[110]  (
    .DIODE(la_data_in[110]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[111]  (
    .DIODE(la_data_in[111]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[112]  (
    .DIODE(la_data_in[112]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[113]  (
    .DIODE(la_data_in[113]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[114]  (
    .DIODE(la_data_in[114]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[115]  (
    .DIODE(la_data_in[115]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[116]  (
    .DIODE(la_data_in[116]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[117]  (
    .DIODE(la_data_in[117]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[118]  (
    .DIODE(la_data_in[118]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[119]  (
    .DIODE(la_data_in[119]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[11]  (
    .DIODE(la_data_in[11]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[120]  (
    .DIODE(la_data_in[120]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[121]  (
    .DIODE(la_data_in[121]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[122]  (
    .DIODE(la_data_in[122]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[123]  (
    .DIODE(la_data_in[123]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[124]  (
    .DIODE(la_data_in[124]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[125]  (
    .DIODE(la_data_in[125]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[126]  (
    .DIODE(la_data_in[126]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[127]  (
    .DIODE(la_data_in[127]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[12]  (
    .DIODE(la_data_in[12]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[13]  (
    .DIODE(la_data_in[13]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[14]  (
    .DIODE(la_data_in[14]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[15]  (
    .DIODE(la_data_in[15]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[16]  (
    .DIODE(la_data_in[16]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[17]  (
    .DIODE(la_data_in[17]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[18]  (
    .DIODE(la_data_in[18]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[19]  (
    .DIODE(la_data_in[19]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[1]  (
    .DIODE(la_data_in[1]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[20]  (
    .DIODE(la_data_in[20]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[21]  (
    .DIODE(la_data_in[21]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[22]  (
    .DIODE(la_data_in[22]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[23]  (
    .DIODE(la_data_in[23]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[24]  (
    .DIODE(la_data_in[24]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[25]  (
    .DIODE(la_data_in[25]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[26]  (
    .DIODE(la_data_in[26]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[27]  (
    .DIODE(la_data_in[27]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[28]  (
    .DIODE(la_data_in[28]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[29]  (
    .DIODE(la_data_in[29]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[2]  (
    .DIODE(la_data_in[2]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[30]  (
    .DIODE(la_data_in[30]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[31]  (
    .DIODE(la_data_in[31]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[32]  (
    .DIODE(la_data_in[32]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[33]  (
    .DIODE(la_data_in[33]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[34]  (
    .DIODE(la_data_in[34]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[35]  (
    .DIODE(la_data_in[35]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[36]  (
    .DIODE(la_data_in[36]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[37]  (
    .DIODE(la_data_in[37]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[38]  (
    .DIODE(la_data_in[38]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[39]  (
    .DIODE(la_data_in[39]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[3]  (
    .DIODE(la_data_in[3]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[40]  (
    .DIODE(la_data_in[40]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[41]  (
    .DIODE(la_data_in[41]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[42]  (
    .DIODE(la_data_in[42]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[43]  (
    .DIODE(la_data_in[43]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[44]  (
    .DIODE(la_data_in[44]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[45]  (
    .DIODE(la_data_in[45]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[46]  (
    .DIODE(la_data_in[46]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[47]  (
    .DIODE(la_data_in[47]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[48]  (
    .DIODE(la_data_in[48]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[49]  (
    .DIODE(la_data_in[49]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[4]  (
    .DIODE(la_data_in[4]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[50]  (
    .DIODE(la_data_in[50]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[51]  (
    .DIODE(la_data_in[51]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[52]  (
    .DIODE(la_data_in[52]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[53]  (
    .DIODE(la_data_in[53]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[54]  (
    .DIODE(la_data_in[54]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[55]  (
    .DIODE(la_data_in[55]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[56]  (
    .DIODE(la_data_in[56]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[57]  (
    .DIODE(la_data_in[57]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[58]  (
    .DIODE(la_data_in[58]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[59]  (
    .DIODE(la_data_in[59]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[5]  (
    .DIODE(la_data_in[5]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[60]  (
    .DIODE(la_data_in[60]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[61]  (
    .DIODE(la_data_in[61]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[62]  (
    .DIODE(la_data_in[62]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[63]  (
    .DIODE(la_data_in[63]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[64]  (
    .DIODE(la_data_in[64]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[65]  (
    .DIODE(la_data_in[65]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[66]  (
    .DIODE(la_data_in[66]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[67]  (
    .DIODE(la_data_in[67]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[68]  (
    .DIODE(la_data_in[68]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[69]  (
    .DIODE(la_data_in[69]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[6]  (
    .DIODE(la_data_in[6]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[70]  (
    .DIODE(la_data_in[70]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[71]  (
    .DIODE(la_data_in[71]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[72]  (
    .DIODE(la_data_in[72]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[73]  (
    .DIODE(la_data_in[73]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[74]  (
    .DIODE(la_data_in[74]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[75]  (
    .DIODE(la_data_in[75]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[76]  (
    .DIODE(la_data_in[76]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[77]  (
    .DIODE(la_data_in[77]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[78]  (
    .DIODE(la_data_in[78]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[79]  (
    .DIODE(la_data_in[79]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[7]  (
    .DIODE(la_data_in[7]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[80]  (
    .DIODE(la_data_in[80]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[81]  (
    .DIODE(la_data_in[81]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[82]  (
    .DIODE(la_data_in[82]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[83]  (
    .DIODE(la_data_in[83]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[84]  (
    .DIODE(la_data_in[84]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[85]  (
    .DIODE(la_data_in[85]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[86]  (
    .DIODE(la_data_in[86]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[87]  (
    .DIODE(la_data_in[87]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[88]  (
    .DIODE(la_data_in[88]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[89]  (
    .DIODE(la_data_in[89]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[8]  (
    .DIODE(la_data_in[8]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[90]  (
    .DIODE(la_data_in[90]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[91]  (
    .DIODE(la_data_in[91]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[92]  (
    .DIODE(la_data_in[92]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[93]  (
    .DIODE(la_data_in[93]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[94]  (
    .DIODE(la_data_in[94]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[95]  (
    .DIODE(la_data_in[95]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[96]  (
    .DIODE(la_data_in[96]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[97]  (
    .DIODE(la_data_in[97]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[98]  (
    .DIODE(la_data_in[98]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[99]  (
    .DIODE(la_data_in[99]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_data_in[9]  (
    .DIODE(la_data_in[9]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[0]  (
    .DIODE(la_oen[0]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[100]  (
    .DIODE(la_oen[100]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[101]  (
    .DIODE(la_oen[101]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[102]  (
    .DIODE(la_oen[102]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[103]  (
    .DIODE(la_oen[103]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[104]  (
    .DIODE(la_oen[104]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[105]  (
    .DIODE(la_oen[105]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[106]  (
    .DIODE(la_oen[106]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[107]  (
    .DIODE(la_oen[107]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[108]  (
    .DIODE(la_oen[108]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[109]  (
    .DIODE(la_oen[109]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[10]  (
    .DIODE(la_oen[10]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[110]  (
    .DIODE(la_oen[110]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[111]  (
    .DIODE(la_oen[111]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[112]  (
    .DIODE(la_oen[112]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[113]  (
    .DIODE(la_oen[113]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[114]  (
    .DIODE(la_oen[114]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[115]  (
    .DIODE(la_oen[115]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[116]  (
    .DIODE(la_oen[116]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[117]  (
    .DIODE(la_oen[117]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[118]  (
    .DIODE(la_oen[118]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[119]  (
    .DIODE(la_oen[119]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[11]  (
    .DIODE(la_oen[11]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[120]  (
    .DIODE(la_oen[120]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[121]  (
    .DIODE(la_oen[121]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[122]  (
    .DIODE(la_oen[122]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[123]  (
    .DIODE(la_oen[123]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[124]  (
    .DIODE(la_oen[124]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[125]  (
    .DIODE(la_oen[125]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[126]  (
    .DIODE(la_oen[126]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[127]  (
    .DIODE(la_oen[127]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[12]  (
    .DIODE(la_oen[12]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[13]  (
    .DIODE(la_oen[13]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[14]  (
    .DIODE(la_oen[14]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[15]  (
    .DIODE(la_oen[15]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[16]  (
    .DIODE(la_oen[16]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[17]  (
    .DIODE(la_oen[17]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[18]  (
    .DIODE(la_oen[18]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[19]  (
    .DIODE(la_oen[19]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[1]  (
    .DIODE(la_oen[1]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[20]  (
    .DIODE(la_oen[20]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[21]  (
    .DIODE(la_oen[21]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[22]  (
    .DIODE(la_oen[22]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[23]  (
    .DIODE(la_oen[23]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[24]  (
    .DIODE(la_oen[24]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[25]  (
    .DIODE(la_oen[25]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[26]  (
    .DIODE(la_oen[26]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[27]  (
    .DIODE(la_oen[27]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[28]  (
    .DIODE(la_oen[28]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[29]  (
    .DIODE(la_oen[29]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[2]  (
    .DIODE(la_oen[2]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[30]  (
    .DIODE(la_oen[30]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[31]  (
    .DIODE(la_oen[31]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[32]  (
    .DIODE(la_oen[32]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[33]  (
    .DIODE(la_oen[33]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[34]  (
    .DIODE(la_oen[34]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[35]  (
    .DIODE(la_oen[35]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[36]  (
    .DIODE(la_oen[36]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[37]  (
    .DIODE(la_oen[37]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[38]  (
    .DIODE(la_oen[38]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[39]  (
    .DIODE(la_oen[39]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[3]  (
    .DIODE(la_oen[3]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[40]  (
    .DIODE(la_oen[40]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[41]  (
    .DIODE(la_oen[41]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[42]  (
    .DIODE(la_oen[42]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[43]  (
    .DIODE(la_oen[43]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[44]  (
    .DIODE(la_oen[44]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[45]  (
    .DIODE(la_oen[45]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[46]  (
    .DIODE(la_oen[46]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[47]  (
    .DIODE(la_oen[47]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[48]  (
    .DIODE(la_oen[48]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[49]  (
    .DIODE(la_oen[49]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[4]  (
    .DIODE(la_oen[4]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[50]  (
    .DIODE(la_oen[50]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[51]  (
    .DIODE(la_oen[51]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[52]  (
    .DIODE(la_oen[52]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[53]  (
    .DIODE(la_oen[53]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[54]  (
    .DIODE(la_oen[54]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[55]  (
    .DIODE(la_oen[55]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[56]  (
    .DIODE(la_oen[56]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[57]  (
    .DIODE(la_oen[57]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[58]  (
    .DIODE(la_oen[58]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[59]  (
    .DIODE(la_oen[59]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[5]  (
    .DIODE(la_oen[5]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[60]  (
    .DIODE(la_oen[60]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[61]  (
    .DIODE(la_oen[61]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[62]  (
    .DIODE(la_oen[62]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[63]  (
    .DIODE(la_oen[63]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[64]  (
    .DIODE(la_oen[64]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[65]  (
    .DIODE(la_oen[65]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[66]  (
    .DIODE(la_oen[66]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[67]  (
    .DIODE(la_oen[67]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[68]  (
    .DIODE(la_oen[68]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[69]  (
    .DIODE(la_oen[69]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[6]  (
    .DIODE(la_oen[6]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[70]  (
    .DIODE(la_oen[70]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[71]  (
    .DIODE(la_oen[71]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[72]  (
    .DIODE(la_oen[72]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[73]  (
    .DIODE(la_oen[73]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[74]  (
    .DIODE(la_oen[74]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[75]  (
    .DIODE(la_oen[75]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[76]  (
    .DIODE(la_oen[76]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[77]  (
    .DIODE(la_oen[77]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[78]  (
    .DIODE(la_oen[78]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[79]  (
    .DIODE(la_oen[79]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[7]  (
    .DIODE(la_oen[7]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[80]  (
    .DIODE(la_oen[80]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[81]  (
    .DIODE(la_oen[81]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[82]  (
    .DIODE(la_oen[82]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[83]  (
    .DIODE(la_oen[83]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[84]  (
    .DIODE(la_oen[84]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[85]  (
    .DIODE(la_oen[85]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[86]  (
    .DIODE(la_oen[86]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[87]  (
    .DIODE(la_oen[87]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[88]  (
    .DIODE(la_oen[88]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[89]  (
    .DIODE(la_oen[89]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[8]  (
    .DIODE(la_oen[8]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[90]  (
    .DIODE(la_oen[90]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[91]  (
    .DIODE(la_oen[91]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[92]  (
    .DIODE(la_oen[92]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[93]  (
    .DIODE(la_oen[93]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[94]  (
    .DIODE(la_oen[94]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[95]  (
    .DIODE(la_oen[95]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[96]  (
    .DIODE(la_oen[96]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[97]  (
    .DIODE(la_oen[97]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[98]  (
    .DIODE(la_oen[98]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[99]  (
    .DIODE(la_oen[99]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_la_oen[9]  (
    .DIODE(la_oen[9]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 ANTENNA_mprj_wb_clk_i (
    .DIODE(wb_clk_i),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 ANTENNA_mprj_wb_rst_i (
    .DIODE(wb_rst_i),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[0]  (
    .DIODE(wbs_adr_i[0]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[10]  (
    .DIODE(wbs_adr_i[10]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[11]  (
    .DIODE(wbs_adr_i[11]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[12]  (
    .DIODE(wbs_adr_i[12]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[13]  (
    .DIODE(wbs_adr_i[13]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[14]  (
    .DIODE(wbs_adr_i[14]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[15]  (
    .DIODE(wbs_adr_i[15]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[16]  (
    .DIODE(wbs_adr_i[16]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[17]  (
    .DIODE(wbs_adr_i[17]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[18]  (
    .DIODE(wbs_adr_i[18]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[19]  (
    .DIODE(wbs_adr_i[19]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[1]  (
    .DIODE(wbs_adr_i[1]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[20]  (
    .DIODE(wbs_adr_i[20]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[21]  (
    .DIODE(wbs_adr_i[21]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[22]  (
    .DIODE(wbs_adr_i[22]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[23]  (
    .DIODE(wbs_adr_i[23]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[24]  (
    .DIODE(wbs_adr_i[24]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[25]  (
    .DIODE(wbs_adr_i[25]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[26]  (
    .DIODE(wbs_adr_i[26]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[27]  (
    .DIODE(wbs_adr_i[27]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[28]  (
    .DIODE(wbs_adr_i[28]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[29]  (
    .DIODE(wbs_adr_i[29]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[2]  (
    .DIODE(wbs_adr_i[2]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[30]  (
    .DIODE(wbs_adr_i[30]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[31]  (
    .DIODE(wbs_adr_i[31]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[3]  (
    .DIODE(wbs_adr_i[3]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[4]  (
    .DIODE(wbs_adr_i[4]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[5]  (
    .DIODE(wbs_adr_i[5]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[6]  (
    .DIODE(wbs_adr_i[6]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[7]  (
    .DIODE(wbs_adr_i[7]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[8]  (
    .DIODE(wbs_adr_i[8]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_adr_i[9]  (
    .DIODE(wbs_adr_i[9]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 ANTENNA_mprj_wbs_cyc_i (
    .DIODE(wbs_cyc_i),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[0]  (
    .DIODE(wbs_dat_i[0]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[10]  (
    .DIODE(wbs_dat_i[10]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[11]  (
    .DIODE(wbs_dat_i[11]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[12]  (
    .DIODE(wbs_dat_i[12]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[13]  (
    .DIODE(wbs_dat_i[13]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[14]  (
    .DIODE(wbs_dat_i[14]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[15]  (
    .DIODE(wbs_dat_i[15]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[16]  (
    .DIODE(wbs_dat_i[16]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[17]  (
    .DIODE(wbs_dat_i[17]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[18]  (
    .DIODE(wbs_dat_i[18]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[19]  (
    .DIODE(wbs_dat_i[19]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[1]  (
    .DIODE(wbs_dat_i[1]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[20]  (
    .DIODE(wbs_dat_i[20]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[21]  (
    .DIODE(wbs_dat_i[21]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[22]  (
    .DIODE(wbs_dat_i[22]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[23]  (
    .DIODE(wbs_dat_i[23]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[24]  (
    .DIODE(wbs_dat_i[24]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[25]  (
    .DIODE(wbs_dat_i[25]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[26]  (
    .DIODE(wbs_dat_i[26]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[27]  (
    .DIODE(wbs_dat_i[27]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[28]  (
    .DIODE(wbs_dat_i[28]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[29]  (
    .DIODE(wbs_dat_i[29]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[2]  (
    .DIODE(wbs_dat_i[2]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[30]  (
    .DIODE(wbs_dat_i[30]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[31]  (
    .DIODE(wbs_dat_i[31]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[3]  (
    .DIODE(wbs_dat_i[3]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[4]  (
    .DIODE(wbs_dat_i[4]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[5]  (
    .DIODE(wbs_dat_i[5]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[6]  (
    .DIODE(wbs_dat_i[6]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[7]  (
    .DIODE(wbs_dat_i[7]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[8]  (
    .DIODE(wbs_dat_i[8]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_dat_i[9]  (
    .DIODE(wbs_dat_i[9]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_sel_i[0]  (
    .DIODE(wbs_sel_i[0]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_sel_i[1]  (
    .DIODE(wbs_sel_i[1]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_sel_i[2]  (
    .DIODE(wbs_sel_i[2]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 \ANTENNA_mprj_wbs_sel_i[3]  (
    .DIODE(wbs_sel_i[3]),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 ANTENNA_mprj_wbs_stb_i (
    .DIODE(wbs_stb_i),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  sky130_fd_sc_hd__diode_2 ANTENNA_mprj_wbs_we_i (
    .DIODE(wbs_we_i),
    .VGND(vssd1),
    .VNB(vssd1),
    .VPB(vccd1),
    .VPWR(vccd1)
  );
  accelerator_top mprj (
    .VGND(vssd1),
    .VPWR(vccd1),
    .io_in(io_in),
    .io_oeb(io_oeb),
    .io_out(io_out),
    .la_data_in(la_data_in),
    .la_data_out(la_data_out),
    .la_oen(la_oen),
    .wb_clk_i(wb_clk_i),
    .wb_rst_i(wb_rst_i),
    .wbs_ack_o(wbs_ack_o),
    .wbs_adr_i(wbs_adr_i),
    .wbs_cyc_i(wbs_cyc_i),
    .wbs_dat_i(wbs_dat_i),
    .wbs_dat_o(wbs_dat_o),
    .wbs_sel_i(wbs_sel_i),
    .wbs_stb_i(wbs_stb_i),
    .wbs_we_i(wbs_we_i)
  );
endmodule
